# Generated by Django 5.1.2 on 2025-07-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cartridgerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cartridgerequest',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartridgerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
