# Generated by Django 5.1.2 on 2025-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cartridgestock_cartridgerequest_issued_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('quantity_added', models.IntegerField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
