# Generated by Django 5.1.2 on 2025-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_stockupdatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupdatelog',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockupdatelog',
            unique_together={('make', 'model', 'updated_on')},
        ),
    ]
