# Generated by Django 5.1.2 on 2025-08-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_stockupdatelog_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupdatelog',
            name='po_number',
            field=models.CharField(editable=False, max_length=25, null=True),
        ),
    ]
