services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn authsystem.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: authsystem.settings
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
    buildFilter:
      paths:
        - authsystem/**

  - type: web
    name: react-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    autoDeploy: true
    buildFilter:
      paths:
        - auth-frontend/**
